using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace RAXY.Notification.Editor
{
    public static class NotificationScriptPaths
    {
        public const string GeneratedMarker = "generated by the Notification Framework";

        public static bool TryGetMonoScriptAssetPath(Type type, out string assetPath)
        {
            assetPath = null;
            if (type == null)
                return false;

            var guids = AssetDatabase.FindAssets(type.Name + " t:MonoScript");
            var matchCount = 0;
            for (var i = 0; i < guids.Length; i++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids[i]);
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (script == null || script.GetClass() != type)
                    continue;

                matchCount++;
                if (assetPath == null)
                    assetPath = path;
            }

            if (matchCount > 1 && assetPath != null)
                Debug.LogWarning(
                    $"[RAXY Hub / Notification] Multiple MonoScripts map to '{type.FullName}'. Using '{assetPath}'.");

            return assetPath != null;
        }

        public static bool TryFindMonoScriptAssetPath(string className, out string assetPath)
        {
            assetPath = null;
            if (string.IsNullOrWhiteSpace(className))
                return false;

            var guids = AssetDatabase.FindAssets(className + " t:MonoScript");
            for (var i = 0; i < guids.Length; i++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids[i]);
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (script == null || script.GetClass() == null)
                    continue;

                if (!string.Equals(script.GetClass().Name, className, StringComparison.Ordinal))
                    continue;

                assetPath = path;
                return true;
            }

            return false;
        }

        public static bool TryGetNotificationIdScriptPath(string namespaceName, out string assetPath)
        {
            assetPath = null;
            var fullName = string.IsNullOrWhiteSpace(namespaceName)
                ? "RAXY.Notification.NotificationId"
                : namespaceName.Trim() + ".NotificationId";

            var guids = AssetDatabase.FindAssets("NotificationId t:MonoScript");
            for (var i = 0; i < guids.Length; i++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids[i]);
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (script == null)
                    continue;

                var type = script.GetClass();
                if (type == null || !string.Equals(type.Name, "NotificationId", StringComparison.Ordinal))
                    continue;

                if (!string.Equals(type.FullName, fullName, StringComparison.Ordinal))
                    continue;

                assetPath = path;
                return true;
            }

            return false;
        }

        public static bool TryGetNotificationTagScriptPath(string namespaceName, out string assetPath)
        {
            assetPath = null;
            var fullName = string.IsNullOrWhiteSpace(namespaceName)
                ? "RAXY.Notification.NotificationTag"
                : namespaceName.Trim() + ".NotificationTag";

            var guids = AssetDatabase.FindAssets("NotificationTag t:MonoScript");
            for (var i = 0; i < guids.Length; i++)
            {
                var path = AssetDatabase.GUIDToAssetPath(guids[i]);
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (script == null)
                    continue;

                var type = script.GetClass();
                if (type == null || !string.Equals(type.Name, "NotificationTag", StringComparison.Ordinal))
                    continue;

                if (!string.Equals(type.FullName, fullName, StringComparison.Ordinal))
                    continue;

                assetPath = path;
                return true;
            }

            return false;
        }

        public static bool IsGeneratedScriptAtPath(string assetPath)
        {
            if (string.IsNullOrWhiteSpace(assetPath))
                return false;

            var absolutePath = ToAbsoluteAssetPath(assetPath);
            if (absolutePath == null || !File.Exists(absolutePath))
                return false;

            return File.ReadAllText(absolutePath).Contains(GeneratedMarker);
        }

        public static bool IsGenerated(Type type)
        {
            if (!TryGetMonoScriptAssetPath(type, out var path))
                return false;

            return IsGeneratedScriptAtPath(path);
        }

        public static void RefreshEntryPaths(NotificationEntry entry, Type requestType, Type viewType)
        {
            if (entry == null)
                return;

            if (requestType != null && TryGetMonoScriptAssetPath(requestType, out var requestPath))
                entry.requestScriptPath = requestPath;

            if (viewType != null && TryGetMonoScriptAssetPath(viewType, out var viewPath))
                entry.viewScriptPath = viewPath;
        }

        public static bool ResolveRequestPath(
            NotificationEntry entry,
            string id,
            string generatedFolder,
            out string assetPath,
            out string message)
        {
            return ResolveScriptPath(
                entry?.requestScriptPath,
                id + "Request",
                generatedFolder,
                out assetPath,
                out message);
        }

        public static bool ResolveViewPath(
            NotificationEntry entry,
            string id,
            string generatedFolder,
            out string assetPath,
            out string message)
        {
            return ResolveScriptPath(
                entry?.viewScriptPath,
                id + "View",
                generatedFolder,
                out assetPath,
                out message);
        }

        static bool ResolveScriptPath(
            string storedPath,
            string className,
            string generatedFolder,
            out string assetPath,
            out string message)
        {
            assetPath = null;
            message = null;

            if (IsValidStoredPath(storedPath))
            {
                assetPath = NormalizeAssetPath(storedPath);
                if (!ValidateWritable(assetPath, out message))
                    return false;

                return true;
            }

            if (TryFindMonoScriptAssetPath(className, out var foundPath))
            {
                assetPath = foundPath;
                if (!ValidateWritable(assetPath, out message))
                    return false;

                return true;
            }

            assetPath = generatedFolder + "/" + className + ".cs";
            if (!ValidateWritable(assetPath, out message))
                return false;

            return true;
        }

        public static bool ResolveNotificationIdPath(
            string storedPath,
            string namespaceName,
            string generatedFolder,
            out string assetPath,
            out string message)
        {
            assetPath = null;
            message = null;

            if (IsValidStoredPath(storedPath))
            {
                assetPath = NormalizeAssetPath(storedPath);
                if (!ValidateWritable(assetPath, out message))
                    return false;

                return true;
            }

            if (TryGetNotificationIdScriptPath(namespaceName, out var foundPath))
            {
                assetPath = foundPath;
                if (!ValidateWritable(assetPath, out message))
                    return false;

                return true;
            }

            assetPath = generatedFolder + "/NotificationId.cs";
            if (!ValidateWritable(assetPath, out message))
                return false;

            return true;
        }

        public static bool ResolveNotificationTagPath(
            string storedPath,
            string namespaceName,
            string generatedFolder,
            out string assetPath,
            out string message)
        {
            assetPath = null;
            message = null;

            if (IsValidStoredPath(storedPath))
            {
                assetPath = NormalizeAssetPath(storedPath);
                if (!ValidateWritable(assetPath, out message))
                    return false;

                return true;
            }

            if (TryGetNotificationTagScriptPath(namespaceName, out var foundPath))
            {
                assetPath = foundPath;
                if (!ValidateWritable(assetPath, out message))
                    return false;

                return true;
            }

            assetPath = generatedFolder + "/NotificationTag.cs";
            if (!ValidateWritable(assetPath, out message))
                return false;

            return true;
        }

        public static bool IsUnderFolder(string assetPath, string folder)
        {
            if (string.IsNullOrWhiteSpace(assetPath) || string.IsNullOrWhiteSpace(folder))
                return false;

            var normalizedPath = NormalizeAssetPath(assetPath);
            var normalizedFolder = folder.Replace('\\', '/').Trim().TrimEnd('/');
            if (!normalizedPath.StartsWith(normalizedFolder + "/", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(normalizedPath, normalizedFolder, StringComparison.OrdinalIgnoreCase))
                return false;

            return true;
        }

        public static bool ValidateWritable(string assetPath, out string message)
        {
            message = null;
            if (string.IsNullOrWhiteSpace(assetPath))
            {
                message = "Script path is empty.";
                return false;
            }

            var normalized = NormalizeAssetPath(assetPath);
            if (normalized.StartsWith("Packages/", StringComparison.OrdinalIgnoreCase))
            {
                message = $"Cannot write generated scripts into package assets: '{normalized}'.";
                return false;
            }

            if (!normalized.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(normalized, "Assets", StringComparison.OrdinalIgnoreCase))
            {
                message = $"Script path must be under Assets: '{normalized}'.";
                return false;
            }

            return true;
        }

        static bool IsValidStoredPath(string path)
        {
            if (string.IsNullOrWhiteSpace(path))
                return false;

            var normalized = NormalizeAssetPath(path);
            var absolute = ToAbsoluteAssetPath(normalized);
            return absolute != null && File.Exists(absolute);
        }

        public static string NormalizeAssetPath(string path)
            => path.Replace('\\', '/').Trim();

        static string ToAbsoluteAssetPath(string assetPath)
        {
            if (string.IsNullOrWhiteSpace(assetPath))
                return null;

            var projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            var full = Path.GetFullPath(Path.Combine(projectRoot, NormalizeAssetPath(assetPath)));
            if (!full.StartsWith(projectRoot, StringComparison.OrdinalIgnoreCase))
                return null;

            return full;
        }
    }
}
