// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the Notification Framework.
// </auto-generated>
// -----------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace RAXY.Notification
{
    public class GetItemView : NotificationView<GetItemRequest>
    {
        [SerializeField]
        TextMeshProUGUI itemNameTmp;

        [SerializeField]
        Image itemIconImg;

        protected override void Bind(GetItemRequest request)
        {
            if (itemNameTmp != null)
                itemNameTmp.text = request.itemName;
            if (itemIconImg != null)
                itemIconImg.sprite = request.itemIcon;
        }
    }
}
