// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the Notification Framework.
// </auto-generated>
// -----------------------------------------------------------------------------

namespace RAXY.Notification
{
    public static class NotificationId
    {
        public const string GetItem = "GetItem";
        public const string UnlockItem = "UnlockItem";
    }
}
