// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the Notification Framework.
// </auto-generated>
// -----------------------------------------------------------------------------

namespace RAXY.Notification
{
    public sealed class UnlockItemRequest : NotificationRequest
    {
        public string itemName { get; }
        public UnityEngine.Sprite itemIcon { get; }

        public UnlockItemRequest()
            : base(NotificationId.UnlockItem)
        {
        }

        public UnlockItemRequest(
            string itemNameValue,
            UnityEngine.Sprite itemIconValue
        )
            : base(NotificationId.UnlockItem)
        {
            itemName = itemNameValue;
            itemIcon = itemIconValue;
        }
    }
}
